import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import Index from "./uploadImages/index";
import { Inter } from "@next/font/google";
import { useState } from "react";
import Modal from "../components/Modal/Modal";
import Navbar from "../components/Navbar/Navbar";
const inter = Inter({ subsets: ["latin"] });

const Home: NextPage = () => {
  const [confirmationModel, setConfirmationModel] = useState(false);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        {setConfirmationModel && (
          <Modal
            isOpen={confirmationModel}
            handleClose={() => setConfirmationModel(!confirmationModel)}
          >
            <Index></Index>
          </Modal>
        )}
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();
  console.log(sessionData);
  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && (
          <span>
            Logged in as {sessionData.user.name}
            {sessionData.user.id}
          </span>
        )}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
